---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: openshift-config
  project: default
  source:
    path: cluster/applications/auth
    repoURL: https://github.com/jharmison-redhat/php-app-migration.git
    targetRevision: main+3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: user.openshift.io
      kind: User
      jsonPointers:
        - /groups
