---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: openshift-cnv
  project: default
  source:
    path: cluster/applications/kubevirt
    repoURL: https://github.com/jharmison-redhat/php-app-migration.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
