---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: database
  name: database
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  running: true
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: database
      spec:
        source:
          http:
            url: https://s3.us-east.cloud-object-storage.appdomain.cloud/roadshowocpvirt/database.qcow2
        storage:
          resources:
            requests:
              storage: 16Gi
          volumeMode: Block
  template:
    metadata:
      labels:
        app: database
        kubevirt.io/domain: database
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
          interfaces:
            - masquerade: {}
              name: default
        resources:
          requests:
            memory: 8Gi
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: database
          name: rootdisk
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
