---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vm-modernization

resources:
- 00-imagestream.yaml
- 01-buildconfig.yaml
- 02-configmap-php-fpm.yaml
- 02-deployment.yaml
- 03-service.yaml
- 04-route.yaml
